# .pre-commit-config.yaml
default_language_version:
  python: python3

default_stages: [pre-commit, pre-push]

repos:
  # ---------- Log wrapper hook (must be first) ----------
  - repo: local
    hooks:
      - id: log-wrapper
        name: Log Wrapper
        language: python
        entry: python .pre-commit-log-wrapper.py
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        verbose: true
        # These options tell pre-commit that this hook doesn't modify files
        # Even though it creates log files, they're in .gitignore
        fail_fast: false
        require_serial: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--explicit-package-bases", "--no-warn-no-return", "--disable-error-code=attr-defined", "--disable-error-code=no-untyped-def", "--disable-error-code=no-any-return", "--disable-error-code=assignment", "--disable-error-code=arg-type", "--disable-error-code=union-attr", "--disable-error-code=var-annotated", "--disable-error-code=list-item", "--disable-error-code=index", "--disable-error-code=operator", "--disable-error-code=call-arg", "--disable-error-code=return-value", "--disable-error-code=name-defined", "--disable-error-code=has-type", "--disable-error-code=override", "--disable-error-code=return", "--disable-error-code=abstract", "--disable-error-code=import-untyped", "--disable-error-code=misc", "--disable-error-code=no-redef", "--disable-error-code=dict-item", "--disable-error-code=call-overload"]
        exclude: ^(archive/|scripts/|src/streamlit_app/utils/__init__\.py)

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-ll", "--configfile", ".bandit.yaml"]

  # ---------- pytest as local hook ----------
  # Disabled for now due to test failures
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: poetry run pytest -q
  #       language: system         # use whatever Python your venv provides
  #       pass_filenames: false    # pytest doesn't need file args
