[project]
name = "sec-filing-analyzer"
version = "0.1.0"
description = "A multi-agent LLM system for analyzing SEC filings and providing financial insights"
authors = [
    {name = "Timothy Wang",email = "timothy.yi.wang@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "edgartools (>=3.14.4,<4.0.0)"
]

[tool.poetry]
name = "sec-filing-analyzer"
version = "0.1.0"
description = "A multi-agent LLM system for analyzing SEC filings and providing financial insights"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "sec_filing_analyzer", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.9.1"
pydantic = "^2.5.2"
python-dotenv = "^1.0.0"
typing-extensions = "^4.8.0"
openai = "^1.12.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"
black = "^23.11.0"
isort = "^5.12.0"
mypy = "^1.7.1"
pylint = "^3.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py39']

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true
